list: $/whilesmarthelpdesk/events/models/sponsor/columns.yaml
modelClass: whilesmarthelpdesk\events\Models\Sponsor
title: Sponsors
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'whilesmarthelpdesk/events/sponsors/update/:id'
